name: UV Publish
description: Publish package to PyPI
branding:
  icon: package
  color: blue

inputs:
  PYTHON_VERSION:
    description: Python version
    required: false
    default: "3.13"
  PYPI_TOKEN:
    description: PyPI API token.
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Install UV
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      shell: bash

    - name: Add UV to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}

    - name: Build package
      run: uv build
      shell: bash

    - name: Publish to PyPI
      run: uv publish --token "${{ inputs.PYPI_TOKEN }}"
      shell: bash
