name: Poetry Publish
description: Publish package to PyPI
branding:
  icon: package
  color: blue

inputs:
  PYTHON_VERSION:
    description: Python version
    required: false
    default: 3.9
  POETRY_VERSION:
    description: Poetry version
    required: false
    default: 1.3.2
  PYPI_USERNAME:
    description: PyPI username. '__token__' by default
    required: false
    default: "__token__"
  PYPI_TOKEN:
    description: PyPI API token.
    required: true
  PYPI_REGISTRY:
    description: PYPI registry address
    required: false
    default: https://upload.pypi.org/legacy/

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Install poetry
      run: pip install poetry==${{ inputs.POETRY_VERSION }}
      shell: bash

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}
        cache: 'poetry'

    - name: Install poetry dependencies
      run: |
        poetry install -n
      shell: bash

    - name: Build and Publish
      run: |
        poetry config repositories.publish ${{ inputs.PYPI_REGISTRY }}
        poetry publish -n -u "${{ inputs.PYPI_USERNAME }}" -p "${{ inputs.PYPI_TOKEN }}" -r publish --build
      shell: bash
