name: Docs Test
description: Run docs tests
branding:
  icon: book-open
  color: yellow

inputs:
  PYTHON_VERSION:
    description: Python version
    required: false
    default: 3.9
  POSTGRES_VERSION:
    description: Postgres major version to use
    required: false
    default: 12
  CONTAINER_NETWORK:
    description: Docker container network to use
    required: false
    default: pgmob-network

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install UV
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      shell: bash

    - name: Add UV to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.PYTHON_VERSION }}

    - name: Install dependencies
      run: uv sync
      shell: bash
      working-directory: docs

    - name: Testing docs
      run: uv run make html
      shell: bash
      working-directory: docs
