name: Docs Test
description: Run docs tests
branding:
  icon: book-open
  color: yellow

inputs:
  PYTHON_VERSION:
    description: Python version
    required: false
    default: "3.13"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install UV
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
      shell: bash

    - name: Add UV to PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      shell: bash

    - name: Setup python
      run: uv python install ${{ inputs.PYTHON_VERSION }}
      shell: bash

    - name: Install dependencies
      run: uv sync --extra psycopg2-binary
      shell: bash
      working-directory: docs

    - name: Testing docs
      run: uv run make html
      shell: bash
      working-directory: docs
